const action = {
    ADD_TEXT: 'ADD_TEXT',
    ADD_STOCKS: 'ADD_STOCKS',
    ADD_FILTERS: 'ADD_FILTERS',
    ADD_AVG: 'ADD_AVG',
    ADD_SEARCH: 'ADD_SEARCH',
    UPD_FILTERS: 'UPD_FILTERS',
    UPD_AVG: 'UPD_AVG',
    DELETE_STOCK: 'DELETE_STOCK',
    UPD_HIGH_AVG: 'UPD_HIGH_AVG',
    UPD_LOW_AVG: 'UPD_LOW_AVG'
}

export default action;