export const COLOR = {
    RESULT: {
        ABOVE_NINTY: { background: 'green', color: 'rgb(255,255,255)' },
        ABOVE_EIGHTY: { background: 'lightgreen', color: 'rgb(255,255,255)' },
        ABOVE_SEVENTY: { background: 'skyblue', color: 'rgb(255,255,255)' },
        ABOVE_SIXTY: { background: 'orange', color: 'rgb(255,255,255)' },
        ABOVE_FIFTY: { background: 'yellow', color: 'rgb(255,255,255)' },
        BELOW_FIFTY: { background: 'red', color: 'rgb(255,255,255)' }
    }
}


export const BANKS = [
    'HDFC Bank',
    'ICICI Bank',
    'St Bk of India',
    'Kotak Mah. Bank',
    'Axis Bank',
    'IndusInd Bank',
    'Bank of Baroda',
    'IDBI Bank',
    'Bandhan Bank',
    'Canara Bank',
    'Punjab Natl.Bank',
    'AU Small Finance',
    'I O B',
    'Yes Bank',
    'Union Bank (I)',
    'IDFC First Bank',
    'Federal Bank',
    'Bank of India',
    'Indian Bank',
    'Central Bank',
    'UCO Bank',
    'Bank of Maha',
    'City Union Bank',
    'RBL Bank',
    'Equitas Sma. Fin',
    'Pun. & Sind Bank',
    'Karur Vysya Bank',
    'CSB Bank',
    'J & K Bank',
    'Ujjivan Small',
    'Fino Payments',
    'DCB Bank',
    'Karnataka Bank',
    'South Ind.Bank',
    'Suryoday Small',
    'Dhanlaxmi Bank'
]

export const FIN_SERVICE = [
    'H D F C',
    'Bajaj Finance',
    'Bajaj Finserv',
    'SBI Cards',
    'Cholaman.Inv.&Fn',
    'Bajaj Holdings',
    'Muthoot Finance',
    'HDFC AMC',
    'Shriram Trans.',
    'Power Fin.Corpn.',
    'I R F C',
    'Max Financial',
    'Aditya Birla Cap',
    'REC Ltd',
    'Sundaram Finance',
    'Nippon Life Ind.',
    'AAVAS Financiers',
    'ICICI Securities',
    'LIC Housing Fin.',
    'Aptus Value Hou.',
    'M & M Fin. Serv.',
    'Poonawalla Fin',
    'L&T Fin.Holdings',
    'Aditya AMC',
    'IIFL Wealth Mgt',
    'UTI AMC',
    'Motil.Oswal.Fin.',
    'CreditAcc. Gram.',
    'Angel One',
    'IIFL Finance',
    'Chola Financial',
    'Capri Global',
    'Shri.City Union.',
    'Manappuram Fin.',
    'I D F C',
    'Can Fin Homes',
    'Indiabulls Hous.',
    'Tata Inv.Corpn.',
    'H U D C O',
    'PNB Housing',
    'Home First Finan',
    'JM Financial',
    'Kama Holdings',
    'Edelweiss.Fin.',
    'JSW Holdings',
    'Dhani Services',
    'Mah. Scooters',
    'Religare Enterp.',
    'Equitas Holdings',
    'Share India Sec.',
    'MAS FINANC SER',
    'Indostar Capital',
    'Bengal & Assam',
    'IIFL Securities',
    'Paisalo Digital',
    'IFCI',
    'Authum Invest',
    'Spandana Sphoort',
    'Anand Rathi Wea.',
    'Pilani Invest.',
    'Sundaram Fin.Hol',
    'Max Ventures',
    'Kirloskar Indus.',
    'Ujjivan Fin.Ser.',
    'Dolat Investment',
    'Ugro Capital',
    'Repco Home Fin',
    'Vardhman Hold.',
    'Sastasundar Ven.',
    'PNB Gilts',
    'Choice Intl.',
    'BF Investment',
    'Centrum Capital',
    'Dhanvarsha Finv.',
    'Nahar Capital',
    'PTC India Fin',
    'Magellanic Cloud',
    '5Paisa Capital',
    'Balmer Law. Inv.',
    'Rane Holdings',
    'Capital India',
    'SMC Global Sec.',
    'Nalwa Sons Invst',
    'Arman Financial',
    'GFL',
    'GIC Housing Fin',
    'Satin Creditcare',
    'Kalyani Invest.',
    'Mangalam Industr',
    'Summit Securitie',
    'Delphi World',
    'VLS Finance',
    'Monarch Networth',
    'Oswal Green Tech',
    'Niyogin Fintech',
    'NBI Indl. Fin.',
    'The Invest.Trust',
    'Tour. Fin. Corp.',
    'Indian Infotech',
    'Crest Ventures',
    'Finkurve Fin.',
    'Cons. Finvest',
    'Muthoot Cap.Serv',
    'Vaarad Ventures',
    'Systematix Corp.',
    'Oswal Agro Mills',
    'Kiran Vyapar',
    'Dhunseri Invest.',
    'SIL Investments',
    'Reliance Capital',
    'Inventure Grow.',
    'CSL Finance',
    'Saraswati Commer',
    'PMC Fincorp',
    'Master Trust',
    'IKAB Securities',
    'Indo Thai Sec.',
    'Apollo Finvest',
    'Prime Securities',
    'Wealth First Por',
    'SREI Infra. Fin.',
    'Jindal Photo',
    'A.K.Capital Serv',
    'BNK Capital',
    'Almondz Global',
    'Moneyboxx Fin.',
    'Jindal Poly Inve',
    'KIFS Financial',
    'Indl.& Prud.Inv.',
    'STEL Holdings',
    'Swiss Military',
    'IL&FS Inv.Manag.',
    'Reliance Home',
    'Baid Leasing',
    'Avonmore Capital',
    'Bombay Oxygen',
    'Mangal Credit',
    'SRG Housing',
    'Capital Trust',
    'Shardul Sec.',
    'A R C Finance',
    'BFL Asset Finves',
    'Star Housing Fin',
    'Indl. Inv. Trust',
    'Coral India Fin.',
    'Guj. Credit Corp',
    'U. Y. Fincorp',
    'ISF',
    'Sakthi Finance',
    'Banas Finance',
    'APM Finvest',
    'McDowell Hold.',
    'BLB',
    'SPS Finquest',
    'Naga Dhunseri',
    'Maha Rashtra Apx',
    'RSD Finance',
    'LKP Finance',
    'Paul Merchants',
    'Ganges Securitie',
    'Pan India Corpor',
    'Yamini Invest',
    'Smartlink Hold.',
    'Startech Fin.',
    'Vibrant Glo. Cap',
    'Motor & Gen Fin',
    'Biogen Pharma',
    'LKP Securities',
    'NCl Res. & Finl.',
    'Pro Fin Capital',
    'Salem Erode Inv.',
    'Assam Entrade',
    'Welspun Investme',
    'Guj. State Fin.',
    'Flomic Global',
    'Palash Securi.',
    'Shalibhadra Fin.',
    'Sharp Investment',
    'Saumya Cons',
    'Available Fin.',
    'Shriram AMC',
    'Ausom Enter.',
    'Apoorva Leasing',
    'GCM Securit.',
    'Advik Capital',
    'Keynote Finan.',
    'Capital Trade Lk',
    'Upsurge Invest.',
    'Stampede Cap.',
    'Lohia Securities',
    'Mukesh Babu Fin.',
    'India Finsec',
    'Inditrade Cap.',
    'IndiaNivesh',
    'Gogia Capital',
    'Aryaman Fin.Serv',
    'Shree Worstex',
    'Sulabh Engineers',
    'Tamboli Capital',
    'Munoth Capital',
    'Emerald Leasing',
    'Stampade Cap-DVR',
    'Times Guaranty',
    'ICDS',
    'Alfred Herbert',
    'Galactico Corpo.',
    'Wallfort Fin.',
    'India Home Loans',
    'Bhartia Bachat',
    'Innovassynth Inv',
    'Suchitra Finance',
    'Acme Resources',
    'Sonal Mercantile',
    'Morarka Finance',
    'Kreon Finnancial',
    'Pioneer Invest',
    'Intec Capital',
    'Ashika Credit',
    'Luharuka Media',
    'Sumedha Fiscal',
    'Utique Enterp.',
    'BCL Enterprises',
    'Dhanlaxmi Cotex',
    'Leading Lea. Fin',
    'TCFC Finance',
    'Arnold Holdings',
    'Joindre Capital',
    'Futuristic Solu',
    'ISL Consulting',
    'Aryaman Capital',
    'Anupam Finserv',
    'TTI Enterprise',
    'P. H. Capital',
    'Ceejay Finance',
    'Odyssey Corpn.',
    'Som Datt Finance',
    'HB Portfolio',
    'Ashirwad Cap.',
    'Akashdeep Metal',
    'HB Stockholdings',
    'Stanrose Mafat.',
    'Viji Finance',
    'CNI Research',
    'Sainik Finance',
    'Oracle Credit',
    'Asit C Mehta Fin',
    'Mega Corp.',
    'West Leisure',
    'Comfort Fincap',
    'Morgan Ventures',
    'Abhinav Capital',
    'Sahara Housing',
    'Premier Cap Serv',
    'IM+ Capitals',
    '3P Land Hold.',
    'B N Rathi Sec.',
    'Key Corp',
    'Ascom Leasing &',
    'Haryana Capfin',
    'Lak. Fin. & Indl',
    'Gilada Finance',
    'Stephanotis Fin.',
    'Escorts Finance',
    'Supra Pacific',
    'SKP Securities',
    'Garbi Finvest',
    'Real Touch Fin',
    'Ind Bank Housing',
    '21st Cent. Mgmt.',
    'Kapashi Commerc.',
    'Wall Street Fin.',
    'Onesource Ideas',
    'Greencrest Finan',
    'AD Manum Finance',
    'Panafic Industri',
    'Khandwala Sec.',
    'Intellivate Capi',
    'Williamson Magor',
    'Alacrity Sec.',
    'Goldline Intl.',
    'Prism Finance',
    'Elixir Capital',
    'Monotype India',
    'Smart Finsec',
    'Bervin Invest.',
    'Transwar.Fin.',
    'Kiduja India',
    'India Cem. Cap.',
    'Nalin Lease Fin.',
    'SMIFS Cap. Mkt.',
    'Jindal Capital',
    'Visco Trade',
    'Cubical Finan',
    'Charter. Capital',
    'Meenakshi Enter.',
    'Intelli.Capital.',
    'Trishakti Elect.',
    'Canopy Finance',
    'Sunshine Capital',
    'Moongipa Sec.',
    'Karnavati Financ',
    'Comfort Comtrade',
    'Econo Trade Indi',
    'Worth Investment',
    'India Lease Dev.',
    'Octal Credit Cap',
    'Optimus Finance',
    'Roselabs Finance',
    'Nam Securities',
    'Indo Asia Financ',
    'Abhishek Finle.',
    'Glance Finance',
    'Easun Capital Ma',
    'Qgo Finance',
    'Oasis Securities',
    'Onelife Capital',
    'Abhinav Leasing',
    'Disha Resources',
    'Sellwin Traders',
    'Srestha Finvest',
    'Ontic Finserve',
    'Franklin Leasing',
    'Goenka Business',
    'Siel Fin. Serv.',
    'Daulat Securitie',
    'BAMPSL Sec.',
    'Vertex Secur.',
    'Nagreeka Cap.',
    'Indus Finance',
    'Global Cap.Mkt.',
    'Libord Finance',
    'Amrapali Capital',
    'Margo Finance',
    'Gemstone Invest.',
    'MPIL Corporation',
    'Shreevatsaa Fin.',
    'Purshottam Inves',
    'KBS India',
    'Cont. Securities',
    'Voltaire Leasing',
    'S P Capital Fin.',
    'Goyal Associates',
    'Dynamic Portfol',
    'Prime Industries',
    'KJMC Corporate',
    'Vishvprabha Ven.',
    'KJMC Financial',
    'Neil Industries',
    'Spark. (I) Finsh',
    'Wagend Infra',
    'Inter Globe Fin',
    'Adinath Exim Res',
    'Naysaa Securi.',
    'Sugal & Damani',
    'Aravali Sec.&Fin',
    'Avasara Finance',
    'MASK INVESTMENTS',
    'Northlink Fiscal',
    'Indo-City Info.',
    'Superior Finleas',
    'Stellar Capital',
    'GCM Capital',
    'Inani Securities',
    'Rapid Invest.',
    'J Taparia Proj',
    'Amerise BioScie',
    'Integra Capital',
    'Mehta Securities',
    'Bharat Bhushan',
    'NPR Finance',
    'Polytex India',
    'Esaar (India)',
    'S R G Securities',
    'DCM Financial',
    'United Credit',
    'S I Cap. & Fin.',
    'Sujala Trading &',
    'Amforge Inds.',
    'J J Finance Corp',
    'Mehta Housg. Fin',
    'Essar Securities',
    'Nidhi Granites',
    'Helpage Finlease',
    'Dalal Street Inv',
    'Mansi Fin.(Chen)',
    'TCI Finance',
    'Enbee Trade',
    'Amarnath Sec.',
    'Manipal Fin. Cor',
    'Shyamkamal Inv',
    'Arunis Abode',
    'Paragon Finance',
    'Focus Business',
    'Seven Hill Inds.',
    'First Custodian',
    'Tokyo Finance',
    'Thirani Projects',
    'Hasti Finance',
    'Money Masters',
    'Sai Capital',
    'Gowra Leasing',
    'Shree Salasar',
    'Decillion Financ',
    'Guj. Lease Fin.',
    'Anjani Finance',
    'Moongipa Capital',
    'Parsharti Invest',
    'NDA Securities',
    'Modern Engineer.',
    'Manraj Hsg.Fin.',
    'Upasana Finance',
    'Trimurthi',
    'Marg Techno-Proj',
    'K K Fincorp',
    'Kanungo Financi.',
    'KD Leisures',
    'Bridge Securitie',
    'Regency Fincorp',
    'Savani Financial',
    'K Z Leasing',
    'Alps Motor Fin',
    'Shiv Om Invst &',
    'Ushakiran Fin.',
    'Shivansh Finserv',
    'Williamson Fin.',
    'Anna Infrastruct',
    'Photon Capital',
    'Libord Securitie',
    'Gallops Enterp.',
    'Modern Shares',
    'SW Investments',
    'Asia Capital',
    'Beryl Securities',
    'Unishire Urban',
    'Classic Leasing',
    'V B Desai Fin.',
    'Golech.Glob.Fin.',
    'Quest Financial',
    'GCM Commodity',
    'SHRI NIWAS L& F.',
    'Trinity League',
    'Galada Finance',
    'G K Consultants',
    'B P Capital',
    'GSB Finance',
    'Multipurpose Trd',
    'Kapil Raj Financ',
    'HB Leasing &Fin.',
    'Bazel Internatio',
    'Sita Enterprises',
    'Adcon Capital',
    'Thirdwave Fin.',
    'Ramsons Projects',
    'Cindrella Fin.',
    'Minolta Finance',
    'Kumbhat Fin.',
    'Madhusudan Sec.',
    'Mehta Integrat.',
    'Ramchandra Leas.',
    'Munoth Fin.Serv.',
    'Krishna Capital',
    'Dharani Finance',
    'Sterling Guaran.',
    'Nikki Glob.Fin.',
    'SSPN FINANCE',
    'Systematix Sec.',
    'Fruition Venture',
    'Ganesh Holdings',
    'Lead Financial S',
    'Regency Trust',
    'Prem Somani Fin.',
    'Gujarat Investa',
    'Step Two Corp.',
    'Harmony Capital',
    'Jagsonpal Fin.',
    'Sungold Capital',
    'Pacheli Indust.',
    'Vani Commercials',
    'Jayabharat Cred.',
    'MILGREY FIN.&INV',
    'KLG Capital',
    'Maruti Sec.',
    'Nicco Uco All.',
    'Mid East Port.',
    'Ekam Leasing',
    'F Mec Intl. Fin.',
    'Kinetic Trust',
    'Vintage Secur.',
    'JPT Securities',
    'Vikalp Securitie',
    'GSL Securities',
    'Futuristic Sec.',
    'Blue Chip India',
    'BOSTON LEA.&FIN.',
    'Capfin India',
    'VCK Cap. Mkt.',
    'Abirami Fin.',
    'Jhaveri Credits',
    'Five X Tradecom',
    'Class. Gl. Fin.',
    'Aneri Fincap',
    'Shree Nidhi Trad',
    'Devki Leasing',
    'Mahan Industries',
    'Dhruva Cap.Serv.',
    'Regal Entertain.',
    'Geetanjali Cred.',
    'Crescent Leasing',
    'Vax Housing Fin.',
    'Brijlaxmi Leas.',
    'Tridev Infra.',
    'Darjeeling Ropew',
    'R R Securities',
    'ATN Intl.',
    'Stellant Secu.',
    'Silicon Valley',
    'Kuber Udyog',
    'Magnanimous Trad',
    'Swastik Safe Dep'
];

export const INS = [
    'SBI Life Insuran',
    'HDFC Life Insur.',
    'ICICI Pru Life',
    'ICICI Lombard',
    'Star Health Insu',
    'General Insuranc',
    'New India Assura'
]